class myStrings:
    
    def __init__(self):
		# super(Root, self).__init__()
        self.strCompany     = "Vervelogic"
        self.strAppDataFolderName  = "Vervelogic_Updates"
        self.strMyAppPublisher = "Vervelogic"
        self.sAppMutex      =   "D0E858DF-985E-4907-B7FB-618FE803C0F9"
        self.strCompanyName_For_Key_Verify     =  "Ajay Sharma"
        self.strCompanyDBName   = "Vervelogic_FR_DB"
        self.strCompanyurl  = "https://www.vervelogic.com/"
        self.strCompany_WebSite = "Company WebSite"
        self.strApptitle    = "Vervelogic Face Recognition"       
        self.strNoFaceFound = "No face found..."
        self.strUnknown     = "unknown"
        self.strPresent     = "Present"
        self.strInputCam    = "Cannot open Input Camera"
        self.strImgFrmInCam = "Cannot receive Image from input camera"
        self.strCamHelpToKnow = "In a group, the camera will help you to identify an 'unknown' person"
        self.strMarkIndi    = "and attendance will be marked individually"
        self.strRedUnknown  = "1. Red Color - Unknown Person"
        self.strBlueStaff   = "2. Blue Color - Staff member but attendance Not mark"
        self.strVersionNo   = "1.0.0.0"
        self.strAppTrialVer = "Trial Version"
        self.strRegisterVer = "Register Version"
        self.strDownloadNewSetup = f"Latest version of {self.strApptitle} is available \n Wish to download now ?\n This might take several minutes."

        # Main Left Btns
        self.strLogin = "Login"
        self.strAddRecords = "Add Records"
        self.strEditRecords = "Edit Records"
        self.strTrainSystem = "Train System"
        self.strAttendanceInfo = "Check Attendance"
        self.strAbout = "About"
        self.strStartFaceRecognition = "Start Face Recognition"
        self.strRemoveFace_Detection = "Remove Face Detection"

        # 5. page
        self.strAttendancePageHeading = "Monthly attendance detailed report"
        self.strEmpID = "Emp. ID"
        self.strEmpName = "Name"
        self.strBtnShowInfo = "Show Details"
        self.strSelMonth = "Select Month"
        self.strSelYear = "Year"
        self.strDept = "Department"
        self.strAddress  = "Address"
        self.strMobileNo = "Mobile No"
        self.strEmpEmail = "Email"
        self.strEmpPost = "Designation"
        self.strEmpDOJ = "Date of Joining \n(dd-mm-yyyy)"
        self.strEmpDOB = "Date of Birth \n(dd-mm-yyyy)"
        self.strEmpGender = "Gender"
        self.strEmpMale = "Male"
        self.strEmpFemale = "Female"
        self.strBtnCaptureImg = "Auto Capture Image"
        self.strBtnSave = "Save"
        self.strMsgNotEmpty = "The Details Must not be empty"
        self.strMsgTitel = "AutoCaptureImage"
        self.strEmailNotValid = "Invalid email address"
        
        # self.strTotalDays = "Total Days:"
        # self.strPresentNo = "Number of Present"
        # self.strAbsentNo = "Number of  Absent"
        # self.strHolidayNo = "Number of on a Holiday"

        # self.strRedLegent = "Absent/ On Leave"
        # self.strGreenLegent = "Present"
        # self.strBlueLegent = "Holiday"

        # 1. login Page
        self.strPageLogin = "Login"
        self.strLoginPageHeading = "Please enter your login details below"
        self.strUserName = "User Name"
        self.strPW = "Password"
        self.strChangePW = r"Change password"
        self.strBtnLogin = "Login"
        self.strBtnForgotPW = r"Forgot password?"
        self.strRegNewUser = r"Register New User"
        self.strPRegNewUserHeading = "Register New User"
        self.strPRegNewUserSubHeading = "Please enter a valid email, it is used in case of user forgot the login password."
        self.strBtnSave = "Save"
        self.strPageTitleNewUser = "New User"
        self.strRegisterSuccessfully = "New User Register Successfully"
        self.strNewUserDiffPW = "Password and Confirmed password should match"


        # 2. Change your password
        self.strPHeading = "Change your password"
        self.strPSubHeading = "To Change your password, please enter old & new password as given below"
        self.strOldPW = "Old Password"
        self.strNewPW = "New Password"
        self.strConfirmPW = "Confirm New Password"
        self.strConfirmMyPW = "Confirm Password"
        self.strBtnCancel = "Cancel"
        self.strBtn1ChangePW = "Change Password"

        self.strBlank = "Please do not leave any field blank."
        self.strPWUpdate = "Password has been modified successfully!!!"
        self.strDiffPW = "Confirmed password and new password should match"
        self.strOldPWNotMatch = "Your Old password does not match"

        #3. "Resetting your password"
        self.strReSetPW = "Resetting your password"
        self.strSubHReSetPW = "To reset your password, please input your email address below"
        self.strBtnReSet = "Reset"
        self.strBtnSendmail = "Sendmail"
        self.strEmail = "Email"
        self.strUsrEmailNotEpty = "User email cannot be empty."
        self.strMailSend = "Mail has been sent, please check your email account"
        self.strInvalidEmail = "Invalid Email, please check the Email format "
        self.strCheckYourNetConnection = "Please cross check your internet connection"
        self.strErrorSendingMail= "Please try again, Some error has come during mail sending"

        #Add record Page
        self.strAddRecordPageH = "Add Employee Information"
        self.strBtnAddNewRecord = "Add New Record"


        #3. page
        self.strHeadingEditRecord = "Search employee information to update the record"
        self.strBtnSearch = "Search Record to Update"
        self.strBtnUpdate = "Update Records"
        self.strBtnDelete = "Delete Record"

        # Training Page
        self.strTrainingPageH = "The system is under the training process please wait"
        self.strBtnStopTrain = "Stop Training"
        self.strBtnStartTrain = "Start Training"
        self.strMsgTxt_trainStop = "Training is Stopped!!!"
        self.strMsgTxt_FUT = "File under Training"
        self.strMsgTxt_NotFindFace = "Didn't find a face"
        self.strMsgTxt_MoreFace = "Found more than one face"
        self.strMsgTxt_Img = "Image"
        self.strMsgTxt_No_Img = "Image not found"
        self.strMsgTxt_NotSuitable = "not suitable for training:"
        self.strMsgTxt_CNNA = "Chose neighbors automatically:"
        self.strMsgTxt_TrainNotComplet = "System Image Training Not Completed!"
        self.strMsgTxt_TrainComplet = "System Image Training Completed!"
        self.strMsgTxt_ReStart_Train = "Re-Start System Training as some images are not suitable"

        # 4. page About       
        self.strHeadingAbout = "About Face Recognition"
        self.strCompanyName = "Company Name:" 
        self.strVNum = "Version Number"
        self.strLicenseStatus = "License Status:"

        # 1. Home Page
        self.strMsgTxt_Title = "Camera"
        self.strMsgTxt_StopCamera = "Please Stop Camera Before moving to the next Page."
        self.strMsgTxt_Login = "Login"
        self.strMsgTxt_PLFirst = "Please Login first"

        #Face Recognition Page
        self.strFR_Heading = "The camera is continuously monitoring the face for attendance"
        self.strFR_btnStop = "Stop"
        self.strFR_MsgProcessStop = "Image Capturing process is stopped!!!"


        self.strMsgCommonTitle = "My Face Recognition"
        self.strMsgRegBeforeLogin = "User not available, please register before Login...."
        self.strUserNameNotEmpty = "Username cannot be empty."
        self.strPWNotEmpty = "Password cannot be empty."
        self.strLoginOK = "Login successfully"
        self.strUser_PW_Incorrect = "The Username or password is incorrect."
        self.strMsgRegBeforeUpdate = "User not available, please register before update...."
        self.strEmailNotMatch = "Please cross check your email as it is not same as register user"
        self.strSaveEmpDataInDB = "Successfully saved employe information in database"
        self.strPlsAddEmPhoto = "Please add employee photo"
        self.strFillAllFileds = "Please fill all information, do not leave any field empty"
        self.strFillAtleastOneOption = "Please fill at least one option to search"
        self.strMsgEmpIDAlreadyUsed = "Please provide new employee id as it is already given to somebody"
        self.strMsgSelectGender = "Please select Gender option"
        self.strMsgSearchUserNotExist = "Search user does not exist"
        self.strMsgPlsTrainTheSystem = "Please train the system after any modification or update in Database"
        self.strMsgConfirm_RemoveUser_FR = "Are you sure to Remove User from face Detection process?"
        self.strBtnRemovefrmFR = "Remove User from face detection"
        
        self.strRemoveFacePageHeading = "After search, user can remove employee face from detection"
        self.strBtnSearchToRemoveFace = "Search User"
        self.strBtnRemoveFace = "Remove user"
        self.strMsgConfirm_UpdateUser = "Are you sure you want to update the user record?"
        self.strUpdateEmpDataInDB = "Successfully Updated employer information in database"
        self.strBtnClearInfo = "Clear Info."
        self.strMsgSearchUserAttendanceNotAvailable = "User Attendance Not Available"
        self.strBtnClear = "Clear Search"
        self.strLegendPresent = "Present"
        self.strLegendAbsent = "Absent"
        self.strLegendHoliday  = "Holiday"
        self.strLegendWorkONHoliday = "Work on holiday"
        self.strTotal_Days_InMonth = "Total days in month"
        self.strTotal_Present_Days = "Total present days"
        self.strTotal_Absent_Days = "Total Absent days"
        self.strTotal_Holiday_Days = "Total holidays"
        self.strTotal_Work_On_Holiday_Days ="Total work on holiday"
        self.strBtnClose = "Close"
        self.strBtnExportData_Excel = "Export To Excel"
        self.strMsgEmpPhotoComplete = "Photo capturing process has been completed"
        self.strMsgStopEmpPhoto = "Stop image capturing process"

        self.strHeadingPageTrialNag = "Authenticating User"
        self.strSubHeadingPageTrialNag = "Validating User Information"
        self.strBtnVerifyKey = "Verify Key"
        self.strMsgTxt_TrialVer = "Trial Version"
        self.strMsgTxt_TrialVerInfo = "Please Register by Entering Product Key "
        self.strMsgTxt_EnterKey = "Please Enter correct key"
        self.strMsgTxt_KeyExpire = "Product key is expired"
        self.strMsgTxt_KeyNotEmpty = "Product Key Can’t be Empty"
        self.strEnterValidKey ="Enter a valid key"
        self.strMsgTxt_FewImageAreNotTrained = "Few images are not suitable for system training!!!\n Please start training process again"
        self.strMsgTxt_AllImagesAreNotSuitable = "All images are not Suitable for training,\n Please add Good Quality images"
        self.strMsg_Mongodb_not_run = "Please start MongoDB..."
        self.strMsgTxt_PlsStartMongoDB_server = "Please establish the mongoserver connection"
        self.strMsgTxt_PlsTraingTheSystem = "Please train the system first..."
        self.strExceedAllottedLimit = "Please Upgrade your product to add more records"
        self.strEmpStatus = "Employe Status"
        self.strEmpWorking = "Working"
        self.strEx_Emp = "Ex-Employee"
        self.strMsgSelectEmpStatus = "Select Employee status"
        self.strCamerNotFound = "Please connect the camera."
        self.strKeyExpireOn = "Product Key expires on:"
        self.strKeyExpired = "Product Key has expired:"
        self.strInValid_DOJ = "Invalid format of Date of Joining"
        self.strInValid_DOB = "Invalid format of Date of Birth"
        self.strJoinDateNotGreatThanNow = "Joining date should not be greater than system date"
        self.strDOBDateNotGreatThanNow = "Date of Birth can’t be greater than system date"
        self.strRegYourPrd  = "Please Register your Product"

        self.strMsgTxt_AlreadyRun = "Another instance of this program is already running"
        self.strFailedCon = "Failed to establish a new connection"
        self.strImproveProperLight_CameraQuality = "Please Capture Image with proper lighting on face or improve Camera quality."
        self.strBtnExportAllData_Excel ="All Emp. Data"
        self.strTakePhoto = "Take Photo"
        self.strPhotoPageHeading = "Proper Light on face before taking User photo"




if __name__ == "__main__":
    strObj = myStrings()


# MsgBox = tk.messagebox.askquestion ('Exit Application','Are you sure you want to exit the application',icon = 'warning')
#     if MsgBox == 'yes':

